# Generated by Django 3.1.5 on 2021-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='laptop',
            field=models.ManyToManyField(to='laptops.Laptops'),
        ),
    ]
