# Generated by Django 3.1.5 on 2021-01-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
        ('employee', '0002_employee_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='laptop',
            field=models.ManyToManyField(blank=True, to='laptops.Laptops'),
        ),
    ]
