# Generated by Django 3.1.5 on 2021-01-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='configuration',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='configuration'),
        ),
    ]
